# GLOBAL VARIABLES
remote_user: jem

# Elastic Search Repo
elastic_repo: elasticsearch.repo

# influxdb repo
influxdb_repo: influxdb.repo

# grafana repo
grafana_repo: grafana.repo

# Logstash conf
logstash_conf: logstash.conf

# Prometheus
prometheus_src: prometheus.service

# Nagios User and Pass
nagios_user: nagiosadmin
nagios_pass: 09170113

# LAMP Variables
domain: jem
owner: jem
group: jem
index_html: index.html
ubuntu_src: jem-ubuntu.conf
centos_src: jem-centos.conf
